################################################################################
# Nostr GPU Relay – minimal config file                                        #
################################################################################

server:
  host: 127.0.0.1      # bind to localhost (socat will proxy to 0.0.0.0:6969)
  port: 8080
  workers: 4           # adjust for CPU cores (Gunicorn forks)

storage:
  # File-backed SQLite; persisted in /data volume
  sqlalchemy.url: sqlite+aiosqlite:///nostr.sqlite3   # Simplified URL format

  # Recommended SQLite pragmas for concurrent reads/writes
  pragmas:
    journal_mode: WAL
    synchronous: NORMAL

gc:
  # Garbage-collect every 5 minutes (default is 300 s)
  interval: 300
  enabled: true

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers: [console]

# Any other nostr-relay sections (rate limits, auth, etc.) can go here.
