################################################################################
# Nostr GPU Relay – minimal config file                                        #
################################################################################

server:
  host: 0.0.0.0              # Bind to all interfaces
  port: 6969                 # Use standard nostr port
  workers: 4                 # adjust for CPU cores (Gunicorn forks)

storage:
  # File-backed SQLite; persisted in /data volume
  sqlalchemy.url: sqlite+aiosqlite:///data/nostr.sqlite3   # Simplified URL format

  # Recommended SQLite pragmas for concurrent reads/writes
  pragmas:
    journal_mode: WAL
    synchronous: NORMAL
  
  # Custom validators - GPU signature validation
  validators:
    - gpu_validator.validate_signature
    - nostr_relay.validators.is_not_too_large
    - nostr_relay.validators.is_recent

gc:
  # Garbage-collect every 5 minutes (default is 300 s)
  interval: 300
  enabled: true

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers: [console]

# GPU signature validator now configured in storage.validators section above
